### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute ....

### ISSUE THREAD

**Issue by YuYun329** [AuvaLab/itext2kg#12]
Thank you to the author for providing a new approach to building the knowledge graph. However, I noticed multiple statements in the source code like 'if "relationships" not in relationships.keys() or relationships == None:' This could lead to an error if 'relationships' is None since NoneType does not have a keys() method. The correct way to avoid errors should be written as: 'if relationships is None or "relationships" not in relationships.keys():' Is this the correct form?

**Comment by lairgiyassir** [comment]
Hello, 

Thank you for pointing out this bug. 
You are right, the two conditions need to be switched. 

I will address this in the upcoming release :).
