### ISSUE TITLE
Recursion error

### ISSUE THREAD

**Issue by lishu2006ll** [AuvaLab/itext2kg#14]
![Uploading image.png…]()

**Comment by lishu2006ll** [comment]
File [/data/itext2kg/itext2kg/ientities_extraction/ientities_extractor.py:42](http://172.16.30.224:8100/lab/tree/itext2kg/itext2kg/itext2kg/ientities_extraction/ientities_extractor.py#line=41), in iEntitiesExtractor.extract_entities(self, context, embeddings, property_name, entity_name_key)
     40 if "entities" not in entities.keys() or entities == None:
     41     print("Not formatted in the desired format, we are retrying ....")
---> 42     self.extract_entities(context=context, entities=entities, embeddings=embeddings, property_name=property_name, entity_name_key=entity_name_key)
     44 return self.data_handler.add_embeddings_as_property_batch(embeddings_function=lambda x:self.langchain_output_parser.calculate_embeddings(x), 
     45                                                           items=entities["entities"],
     46                                                           property_name=property_name,
     47                                                           item_name_key=entity_name_key,
     48                                                           embeddings=embeddings)

TypeError: iEntitiesExtractor.extract_entities() got an unexpected keyword argument 'entities'

**Comment by lairgiyassir** [comment]
Hello, 

I could not see the screenshot :(.
Could you resend it ? 

Ty
