### ISSUE TITLE
网络

### ISSUE THREAD

**Issue by ganjue153** [AuvaLab/itext2kg#16]
我在运行的时候，碰到网洛连接问题，是什么原因呢（我水平不是很高，虚心请教）

**Comment by ganjue153** [comment]
由于目标计算机积极拒绝，无法连接。这个是因为防火墙的问题吗？

**Comment by lairgiyassir** [comment]
你使用的是哪种大型语言模型？OpenAI的GPT模型吗？

**Comment by ganjue153** [comment]
我现在在学习使用bert模型，不知道应该如何配置

**Comment by YuYun329** [comment]
> 我现在在学习使用bert模型，不知道应该如何配置

使用itext2kg不需要对bert模型有很深的理解，你需要了解openai的api格式，如果你使用的是本地语言模型，你可以使用xinference、ollama等模型部署工具来提供本地模型的推理接口。
如果你自定义并训练了一个BERT-base的语言模型，你可以仿照openai的api格式提供模型的推理接口。
当然，最方便的是获取一个gpt系列的api key，用os.environ配置好环境变量即可

**Comment by lairgiyassir** [comment]
@YuYun329  Thank you ;)
