### ISSUE TITLE
Does the code support big models other than GPT?

### ISSUE THREAD

**Issue by fireSunset** [AuvaLab/itext2kg#18]
I want to try your code, butI don't have   key for OPENAI, is it convenient to change the code to support other big model forms, thanks a lot!

**Comment by lairgiyassir** [comment]
Hello, 

Which model would you use? 

iText2KG supports all the chat models supported by langchain. :https://python.langchain.com/v0.2/docs/integrations/chat/

**Comment by fireSunset** [comment]
I usually use Tongyi Qwen and BGE on Hugging Face, they are supported, thanks!

**Comment by lairgiyassir** [comment]
If they are on huggingface, you can follow this tutorial :

https://python.langchain.com/v0.2/docs/integrations/chat/huggingface/

**Comment by fireSunset** [comment]
![image](https://github.com/user-attachments/assets/62070645-0307-49a6-897c-4f5e29b33cb9)
![image](https://github.com/user-attachments/assets/0568706b-b276-45ab-ab1e-8358f483139a)
I tried switching to a different model and ran the ollama code in different_llm_models_scientific_articles.ipynb, but it kept throwing errors and did not extract any relationships.

**Comment by lairgiyassir** [comment]
Hello, 

The main problem of these smaller LLM models is their inability to format (parse) the output. 
We have had the same problem in #6. 

Please consider using qwen2.5:7b
Or upgrade it to qwen2:72b https://ollama.com/library/qwen2:72b

Tell me if qwen2.5 solved the issue. 
:)

**Comment by fireSunset** [comment]
![image](https://github.com/user-attachments/assets/d3382fe8-b96b-45b5-a546-4475a252d7d5)
I tried qwen2.5:7b, and the code ran successfully, but the extracted results still have redundancy issues.😆

**Comment by lairgiyassir** [comment]
With qwen2.2:7b, the extracted entities are not bad! 
I see some hallucinations in the extracted relationships. For example Merges_Similar..

Do you see other redundancies? 

Unfortunately, there is no other solution than choosing llm models with bigger sizes. Could you try qwen25:14B , or 32B or 72B ?
