### ISSUE TITLE
How to save the generated knowledge graph locally?

### ISSUE THREAD

**Issue by ImsuperSH** [AuvaLab/itext2kg#21]
Knowledge graph contains Numpy array, so it cannot be serialized to json directly. Any ideas pls?

**Comment by lairgiyassir** [comment]
Hello, 

You can store the constructed graph using pickle. 

`import pickle

with open("./kg.pkl", "wb") as file:
    pickle.dump(kg, file)`

Or retrieve an existing graph : 

import pickle

`with open("./kg.pkl", "rb") as file:
    kg = pickle.load(file)`
