### ISSUE TITLE
About evaluation codes.

### ISSUE THREAD

**Issue by hhy-huang** [AuvaLab/itext2kg#5]
Hi, thank you for your impressive work!

But I'm really interested in your dataset and evaluation benchmark, I didn't find the evaluation scripts in your repo. Could you please release the evaluation scripts?

**Comment by lairgiyassir** [comment]
Hello,

Thank you :)

Approximately all our evaluations were done manually.

**Module 1: Ensuring the concordance of the extracted information with the schema and the semantics of the input documents.** We handled this by generating 5 CVs, selecting 5 articles, and reviewing 5 company websites. For each distilled document (in JSON or dictionary format), we manually checked whether the information was consistent with the original text. This was done for each "key" and "value" pair in the distilled document.

**Module 2: Regarding the extracted triplets and the quality of entity/relation resolution,** I used the dataset provided by https://github.com/OthmaneKabal/G-T2KG/tree/main/data/corporas. However, we observed that it is not exhaustive, especially for triplets implied by the text but not directly stated. Therefore, we performed a manual check on the extracted triplets to ensure they were consistent with the context.

Module 3: We calculated the false discovery rates for entity/relation resolution (from the dataset generated in module 1) by dividing the number of unresolved entities/relations by the total number of extracted entities and relations. 

**Threshold estimation:** To estimate the threshold for merging entities and relationships based on cosine similarity, a dataset of 1,500 similar entity pairs and 500 relationships, inspired by various domains (e.g., news, scientific articles, HR practices), was generated using GPT-4 and is available in the iText2KG GitHub repository. Entities and relationships were vectorized using the pre-trained model text-embedding-3-large. I can share with you the code of this estimation if you want :)
