### ISSUE TITLE
is this a bug in itext2kg.py ?

### ISSUE THREAD

**Issue by GanchengWang** [AuvaLab/itext2kg#7]
itext2kg\graph_integration\itext2kg.py
line 153
relationships = self.irelations_extractor.extract_relations(context= sections, entities=list(map(lambda w:w["name"], processed_entities)))
maybe context= sections[i] ？

**Comment by lairgiyassir** [comment]
Hello, 

Good remark! 
It is a bug. 

I will correct it :)
