### ISSUE TITLE
Package Import Issues

### ISSUE THREAD

**Issue by hsk1079** [AuvaLab/itext2kg#8]
There are a few issues with calling this line:

```
from itext2kg import DocumentDistiller
```

when I checked the [__init__.py], the Document Distiller is called differently:

```
from .documents_distiller import DocumentsDisiller
from .graph_integration import GraphIntegrator, iText2KG
```
DocumentsDisiller in the _init_.py is spelled wrong.

Can you please check and update these files?

Thanks

**Comment by lairgiyassir** [comment]
Hello,

Thank you for reporting that. 
I will correct it :).
