### ISSUE TITLE
Regarding the use case

### ISSUE THREAD

**Issue by yuemeng200** [AuvaLab/itext2kg#9]
I would like to use this repository to extract characters and relationships from long novels. Is this feasible? Thanks!

**Comment by lairgiyassir** [comment]
Hello,

This is a very interesting use case. I will work on it over the next few days and share a notebook in this GitHub repository.

Here are some insights on how to approach it:

1. If the document is too large, ensure that your API key or local model can handle it.
2. You can bypass the Document Distiller step and pass the **novel sections directly as semantic** blocks to iText2KG. Just pay attention to your LLM's context window. If the section fits within the context window, you're good. If it's too large, you can split it.
3. iText2KG will handle entity/relation resolution based on the semantic blocks you provide.

I'm excited to test this use case!
